version: "3.9"

services:
  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram-chat-bot-1
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .:/telegram-chat-bot-1
    command: ["python", "main.py"]